### ISSUE TITLE
Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by Herteby** [kraklin/elm-debug-transformer#1]
I'm having a weird issue, I'm using it just as suggested:
```
import ElmDebugger from 'elm-debug-transformer';
ElmDebugger.register();
```
But for some reason ElmDebugger is undefined.

I can see that it's installed in node_modules, and I get no compiler error.
Using Webpack 4.14.0, and haven't had this issue with any other package

**Comment by kraklin** [comment]
Thank you for the issue. It looks like bad import. Can you try 
```
import {register} from 'elm-debug-transformer'

register();
```

**Comment by Herteby** [comment]
Cool! Both methods fixed it. Weird bug though.

Really nice package! :smile:

**Comment by kraklin** [comment]
Thanks for confirmation it is working. It is not a weird bug though. The package exports only `register()` so the import was wrong in README. Thanks for pointing that out. I'd probably never find it by myself.
