### ISSUE TITLE
Inefficient space usage leading to crash on available memory.

### ISSUE THREAD

**Issue by turboMaCk** [kraklin/elm-debug-transformer#11]
There seems to be inefficient space usage when this plugin parses large messages (loging a lot of data).

- chrome: `paused before potential out of memory crash`
- firefox: `webpage slowing down alert` @janiczek reported even browser crash

This is caused by this plugin and not the app itself. We're not sure if it's a memmory leak or just inefficient memory usage for large inputs.

**Comment by kraklin** [comment]
Fixed by release 1.0.0-rc4
