### ISSUE TITLE
Edge: SCRIPT1028: Expected identifier, string or number

### ISSUE THREAD

**Issue by jesse-c** [kraklin/elm-debug-transformer#12]
When running in Edge on Windows 10 (using a development ISO from Microsoft), the error `SCRIPT1028: Expected identifier, string or number` appears.

I tried looking at the generated JS to get an idea of what was happening, and it might be because it contains the spread operator (`...`) which apparently isn't supported by Edge.

**Comment by kraklin** [comment]
Hi @jesse-c - can you try it with beta version installed? I have just tried that in my Win10's Edge and it seems to be working.

You can install it with 
```
npm install elm-debug-transformer@1.0.0-rc5
```

**Comment by jesse-c** [comment]
Yup, it's working alright now. Thanks.
