### ISSUE TITLE
A possible bug (Nothing Nothing)

### ISSUE THREAD

**Issue by Janiczek** [kraklin/elm-debug-transformer#17]
![bug](https://user-images.githubusercontent.com/149425/69734359-1dd73680-112f-11ea-832f-77b2968d6341.png)

Seems like the parser thinks there is `Nothing` constructor with argument `Nothing`, while in reality these are two separate single-level Nothings.

The original type is
```elm
type CacheKey
    = CacheKey DatapointCode (Maybe AudienceId) (Maybe SegmentId)
```

The debug message before parsing:
```
cache before merging: AnyDict { dict = Dict.fromList [(("q999_99",(0,""),(0,"")),(CacheKey (Id "q999_99") Nothing Nothing,Success { audiencePercentage = 100, datapointPercentage = 100, index = 100, responsesCount = 30622, weightedUniverse = 205787975 })),(("q999_99",(1,"7134"),(0,"")),(CacheKey (Id "q999_99") (Just (Id "7134")) Nothing,Failure (CustomError "96bdfc0b319eed1f7a379ba4b26486c7" (InvalidProjectsCombination (QueryId "86550699-1a81-41fe-9a34-a2e88895df24") ("gwi-hispanic",["core"])))))], toKey = <function> }
```

(see the `CacheKey (Id "q999_99") Nothing Nothing` part)

**Comment by kraklin** [comment]
It should be fixed now - it was a little bit harder than I thought it would be but I uncover another bug that have been sitting there. Thank you @Janiczek
