### ISSUE TITLE
Clarify set up instruction in README

### ISSUE THREAD

**Issue by AlienKevin** [kraklin/elm-debug-transformer#22]
The part of "Register the console debugger in your main JS file **before you initialize Elm application**" is incomplete because you actually have to register **before importing Elm**.
Registering *before initializing Elm application* does not work:
```
<body>
  <main></main>
  <script src="https://unpkg.com/elm-debug-transformer@latest/dist/elm-console-debug.js"></script>
  <script src="elm.js"></script>
  <!-- register before initializing Elm but after importing elm.js -->
  <!-- DOES NOT WORK!!! -->
  <script>ElmConsoleDebug.register({simple_mode: false, debug: false, limit: 10000});</script>
  <script>
    var app = Elm.Main.init({ node: document.querySelector('main') });
  </script>
</body>
```
Registering *before importing Elm* does work:
```
<body>
  <main></main>
  <script src="https://unpkg.com/elm-debug-transformer@latest/dist/elm-console-debug.js"></script>
  <script>ElmConsoleDebug.register({simple_mode: false, debug: false, limit: 10000});</script>
  <script src="elm.js"></script>
  <script>
    var app = Elm.Main.init({ node: document.querySelector('main') });
  </script>
</body>
```
I really like the work you did and I'm not intending to be picky. I'd appreciate if you can add a full usage example like the one below to README:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Elm App</title>
</head>
<body>
  <main></main>
  <script src="https://unpkg.com/elm-debug-transformer@latest/dist/elm-console-debug.js"></script>
  <script>ElmConsoleDebug.register({simple_mode: false, debug: false, limit: 10000});</script>
  <script src="elm.js"></script>
  <script>
    var app = Elm.Main.init({ node: document.querySelector('main') });
  </script>
</body>
</html>
```

**Comment by kraklin** [comment]
Thank you @alienkevin 

You are not picky, that README is really incomplete in some ways. Also I have never tried to register the Debug Transformer after Elm, so it didn’t occur to me that it can be a problem.


Can you make PR to improve README, I’d be more than happy to merge it ;)

**Comment by kraklin** [comment]
On the other hand, it should not be behaving like this as I’m hooking up on console.log and elm initialization should not temper with it in any way... let me investigate this 🤔

**Comment by AlienKevin** [comment]
@kraklin Thanks for your attention and sorry for responding late. I made a PR for the readme just now.
