### ISSUE TITLE
Error when you console.log(undefined)

### ISSUE THREAD

**Issue by ursi** [kraklin/elm-debug-transformer#25]
I'm getting the following error when I `console.log(undefined)`
```
C:\...\node_modules\elm-debug-transformer\dist\elm-console-debug.js:9 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at console.P.console.log (C:\...\node_modules\elm-debug-transformer\dist\elm-console-debug.js:9)
```

**Comment by kraklin** [comment]
@ursi thanks for reporting this - I'm diving into it straight away ;)

**Comment by kraklin** [comment]
So @ursi - it should be fixed. Can you try version `1.0.5` and let me know if it is working for you?

**Comment by ursi** [comment]
looks like it's workin!

**Comment by kraklin** [comment]
Cool. Let me know if it will misbehave ;) Happy debugging
