### ISSUE TITLE
console.logs in javascript not working

### ISSUE THREAD

**Issue by simonh1000** [kraklin/elm-debug-transformer#4]
love the tool!

I have a couple of console logs that fire in my javascript after registering the transformer and before the elm code is init-ed. I no longer see any content for these now.

for example `console.log("builder flags:", flags);` puts the string into console, but not the flags object

**Comment by kraklin** [comment]
@simonh1000 Nice catch. I have only passed the first argument. It should be fixed with version 0.0.7 - can you please test it?

**Comment by simonh1000** [comment]
looks good
