### ISSUE TITLE
Debug.log "" False puts null in console

### ISSUE THREAD

**Issue by simonh1000** [kraklin/elm-debug-transformer#5]
repro: add `_ = Debug.log "False" False` to code

**Comment by kraklin** [comment]
Thank you for the Issue, it is already solved in the upcoming version 1.0.0 (which I hope to be out pretty soon). I'll do a quick patch to the `0.0.x` versions though ;)

**Comment by kraklin** [comment]
@simonh1000 It should be fixed with version 0.0.7 - can you please test it?

**Comment by simonh1000** [comment]
that looks good :-)
thanks again
