### ISSUE TITLE
Error when `console.log`-ing JS event

### ISSUE THREAD

**Issue by Janiczek** [kraklin/elm-debug-transformer#8]
Just saw this error when debugging something in the devtools console... Probably doesn't affect anything around it, but I guess the formatter should pass it to the original implementation *silently* instead of throwing an error?
```
Custom Formatter Failed: Uncaught TypeError: Illegal invocation
```
![event](https://user-images.githubusercontent.com/149425/61454483-508f4800-a961-11e9-8bf4-2ebe404fa37e.png)

**Comment by kraklin** [comment]
@Janiczek Are you able to reproduce the error? If so, pleas turn on "debug" mode - add `debug: true`to the `register function 

```
register({..., debug: true})
``` 

to output the original message before formatting and paste the problematic console message here please.

**Comment by Janiczek** [comment]
Right now I can't :confused: So I'm closing this. Sorry for the false alarm; if something similar pops up, I'll know to turn the debug flag on :slightly_smiling_face:
